name: Build Grasshopper Plugin

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest # For a list of available runner types, refer to

    env:
      Solution_Name: Tunny.sln
      Plugin_File_Name: Tunny

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download python & wheel zip
        shell: powershell
        run: |
          cd Tunny/Lib
          ./setup-python-lib.bat
          cd ../..

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Build the application
        run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Copy items to /Release dir
        shell: powershell
        run: |
          cp ./Examples ./Release/Examples -recurse
          cp ./LICENSE ./Release/LICENSE.txt
          cp ./PYTHON_PACKAGE_LICENSES ./Release/PYTHON_PACKAGE_LICENSES.txt
          cp ./Tunny/bin/Release/net48 ./Release/Tunny -recurse

      - name: Upload release build of plugin as artefact
        uses: actions/upload-artifact@v2
        with:
          name: Tunny
          path: |
            ./Release
          retention-days: 7
